name: Build Jekyll site
on:
  pull_request:
    types: [ synchronize, opened, reopened ]
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: actions/jekyll-build-pages@v1
